# pull official base image
FROM node:12

# set working directory
WORKDIR /app

EXPOSE 3000

# install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn
RUN yarn global add react-scripts@4.0.0

# add app
COPY . ./

# start app
CMD ["yarn", "dev"]