# pull official base image
FROM node:12-alpine

RUN mkdir /app

# set working directory
WORKDIR /app

EXPOSE 3000

# add app
COPY . ./

# install app dependencies
RUN yarn

# start app
CMD ["yarn", "dev"]